raw_dir: "input/raw"
fastq_dir: "input/fastq"
index_dir: "input/refdata-gex-GRCh38-2024-A/star/"
bam_dir: "output/bam"
qc_dir: "output/qc"
counts_dir: "output/counts"
project_curls_path: "config/proyects_metadata_curls.csv"
metadata_path: "config/proyects_metadata_samples_fastqs.csv"
genome_fasta: "input/refdata-gex-GRCh38-2024-A/fasta/genome.fa"
gtf: "input/refdata-gex-GRCh38-2024-A/genes/genes.gtf.gz"
output_dir: "output"
ref_dir: "input/ref"
star_threads: 20
sjdb_overhang: 99            # set to max observed R2 length - 1
genomeSAindexNbases: 14      # recommended for human
whitelists:
  "10x3'v2": "input/whitelist/737K-august-2016.txt"
  "10x3'v3": "input/whitelist/3M-february-2018.txt"
  "10x5'v1": "input/whitelist/737K-august-2016.txt"
scripts:
  download_project: "workflow/scripts/download_project.py"
  filter_and_preprocess: "workflow/scripts/filter_and_preprocess_fastqs.py"
  fastq_vibe_check: "workflow/scripts/fastq_vibe_check.py"
  generate_index: "workflow/scripts/generate_index.sh"
  map_reads: "workflow/scripts/map_reads.sh"
  matrix_counts: "workflow/scripts/matrix_counts.sh"
counts_layer: "filtered"   # options: "filtered" or "raw"
# Keep "Gene" for now.
solo_features:
  - "Gene"                 # exon-only (typical scRNA-seq)
  # - "GeneFull"           # add if you also want exon+intron (snRNA / velocity)
  # - "SJ"                 # splice junctions
  # - "Velocyto"           # spliced/unspliced/ambiguous; requires "Gene" also

project: null
